"""rename address

Revision ID: 590319c06c37
Revises: 9d781e3997c3
Create Date: 2024-01-30 06:31:28.935934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590319c06c37'
down_revision = '9d781e3997c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
